plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id "com.modrinth.minotaur" version "2.+"
    id 'maven-publish'
    id 'com.diffplug.spotless' version '8.+'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

spotless {
    java {
        target 'src/*/java/**/*.java'

        googleJavaFormat("1.33.0")

        toggleOffOn()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

repositories {
    maven { url "https://maven.bawnorton.com/releases" }
    maven { url "https://maven.enjarai.dev/mirrors" }
    maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://maven.nucleoid.xyz' }
    maven { url 'https://jitpack.io' }
    maven { url "https://api.modrinth.com/maven" }
    mavenCentral()
}

fabricApi {
    configureDataGeneration()
}

loom {
    accessWidenerPath = file("src/main/resources/servercosmetics.accesswidener")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.4")))
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:0.3.7-beta.3")))
    include(implementation("eu.pb4:sgui:${project.sgui_version}"))
    include(implementation("me.lucko:fabric-permissions-api:${project.fabric_permissions_api_version}"))

    include(implementation 'com.github.Carleslc.Simple-YAML:Simple-Yaml:1.8.4')

    include(implementation 'org.xerial:sqlite-jdbc:3.46.0.1')
    include(implementation 'com.j256.ormlite:ormlite-jdbc:6.1')
    include(implementation 'com.j256.ormlite:ormlite-core:6.1')

    implementation("eu.pb4:polymer-core:${polymer_version}")
    implementation("eu.pb4:polymer-blocks:${polymer_version}")
    implementation("eu.pb4:polymer-resource-pack:${polymer_version}")
    implementation("eu.pb4:polymer-virtual-entity:${polymer_version}")
    implementation("eu.pb4:polymer-autohost:${polymer_version}")

    implementation(include("eu.pb4:placeholder-api:${placeholder_api_version}"))

    testImplementation "org.junit.jupiter:junit-jupiter:6.1.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
    processResources.exclude('.cache/**/*')
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
        // Automatically configured for GitHub Packages if env vars exist
        if (System.getenv("GITHUB_TOKEN")) {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/${System.getenv("GITHUB_REPOSITORY")}")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

if (System.getenv("MODRINTH_TOKEN")) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = 'rpTNWjZH'// This can be the project ID or the slug
        versionNumber = "${project.version}"
        versionType = "release" // This is the default -- can also be `beta` or `alpha`
        uploadFile = jar
        gameVersions = [((String) project.minecraft_version)]
        changelog = System.getenv("CHANGELOG")
        loaders = ["fabric"]

        dependencies {
            required.project "polymer"
        }

        syncBodyFrom = rootProject.file("README.md").text
        tasks.modrinth.dependsOn(tasks.modrinthSyncBody)
    }
    jar {
        finalizedBy project.tasks.modrinth
    }
}
